import AdminPage from "@/components/AdminPage";
import "./globals.css";
import { Orbitron } from "next/font/google";
const orbitron = Orbitron({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout() {
  return (
    <html lang="en">
      <body className={orbitron.className}>
        <AdminPage></AdminPage>
      </body>
    </html>
  );
}
